name=input("Enter the name (First letter in capital letter).:")

for letter in name:
    if letter=='A':
        print('@',end=' ')
    elif letter=='B':
        print('$',end=' ')
    elif letter=='C':
        print('-',end=' ')
    elif letter=='D':
        print('a',end=' ')
    elif letter=='E':
        print('k',end=' ')
    elif letter=='F':
        print('#',end=' ')
    elif letter=='G':
        print('?',end=' ')
    elif letter=='H':
        print('R',end=' ')
    elif letter=='I':
        print('q',end=' ')
    elif letter=='J':
        print('%',end=' ')
    elif letter=='K':
        print('~',end=' ')
    elif letter=='L':
        print('z',end=' ')
    elif letter=='M':
        print(')',end=' ')
    elif letter=='N':
        print('+',end=' ')
    elif letter=='O':
        print('d',end=' ')
    elif letter=='P':
        print('x',end=' ')
    elif letter=='Q':
        print('h',end=' ')
    elif letter=='R':
        print('!',end=' ')
    elif letter=='S':
        print('i',end=' ')
    elif letter=='T':
        print('(',end=' ')
    elif letter=='U':
        print('}',end=' ')
    elif letter=='V':
        print('a',end=' ')
    elif letter=='W':
        print('b',end=' ')
    elif letter=='X':
        print('g',end=' ')
    elif letter=='Y':
        print('s',end=' ')
    elif letter=='Z':
        print('t',end=' ')
    elif letter=='a':
        print('G',end=' ')
    elif letter=='b':
        print('E',end=' ')
    elif letter=='c':
        print('I',end=' ')
    elif letter=='d':
        print('Q',end=' ')
    elif letter=='e':
        print('R',end=' ')
    elif letter=='f':
        print(']',end=' ')
    elif letter=='g':
        print('{',end=' ')
    elif letter=='h':
        print('[',end=' ')
    elif letter=='i':
        print('.',end=' ')
    elif letter=='j':
        print('B',end=' ')
    elif letter=='k':
        print('Z',end=' ')
    elif letter=='l':
        print('V',end=' ')
    elif letter=='m':
        print('N',end=' ')
    elif letter=='n':
        print('P',end=' ')
    elif letter=='o':
        print('"',end=' ')
    elif letter=='p':
        print(';',end=' ')
    elif letter=='q':
        print('T',end=' ')
    elif letter=='r':
        print('U',end=' ')
    elif letter=='s':
        print('Y',end=' ')
    elif letter=='t':
        print(':',end=' ')
    elif letter=='u':
        print('/',end=' ')
    elif letter=='v':
        print('H',end=' ')
    elif letter=='w':
        print('^',end=' ')
    elif letter=='x':
        print('`',end=' ')
    elif letter=='y':
        print('h',end=' ')
    elif letter=='z':
        print('s',end=' ')
    elif letter==' ':
        print('1',end=' ')
    else:
        print("Please enter valid name....")